-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'WORKOUT_REMINDER';
ALTER TYPE "NotificationType" ADD VALUE 'STREAK_ALERT';
ALTER TYPE "NotificationType" ADD VALUE 'ACHIEVEMENT_TEASE';
ALTER TYPE "NotificationType" ADD VALUE 'SOCIAL_MOTIVATION';
